

poolableConnection.validate.fastFail=此连接上预先抛出了致命的 SQLException。

poolingDataSource.factoryConfig=PoolableConnectionFactory 未连接到连接池。请调用 setPool() 修复此配置。

swallowedExceptionLogger.onSwallowedException=一个内部对象池吞并了一个异常。
